
module.exports={
    uiUrl: '',
    url: 'https://bet600.preprod.fsbtech.com/fsb-api-rest',
    authUsername: 'bet600',
    authPassword: 'tFjE2WgqWh',
    clientId: 'bet600web',
    clientSecret: '6jLdCqUOuK',
    accessTokenGlobal: '2b92bfda-ba25-4f72-9fe1-54e56f2e7cc7',
    userNameGlobal: 'QABT6002504',
    passwordGlobal: 'Test1234',
    custodianUrl: 'https://custodian.preprod.fsbtech.com/',
    custodianUsername: 'PavanD',
    custodianPassword: 'h#0pEXhhttos',
    userNameFullCoverBet: 'APIJenningsbet3',
    passwordFullCoverBet: 'APIPassword123',
    userNameForeCastBets: 'APIJenningsbet3',
    passwordForeCastBets: 'APIPassword123',
    userName7FDTo11FDBet: 'APIJenningsbet1',
    password7FDTo11FDBet: 'APIPassword123',
    userName11FDTo15FDBet: 'APIJenningsbet2',
    password11FDTo15FDBet: 'APIPassword123',
    currencyCode: 'GBP',
    randomDeposit: '',
    requestBBody: ''
}