
module.exports={
    uiUrl: '',
    url: 'https://betgoodwin.qa.fsbtech.com/fsb-api-rest',
    authUsername: 'betgoodwin',
    authPassword: 'B3tG00Dwin!*',
    clientId: 'betgoodwinweb',
    clientSecret: 'QIsReY5p8X',
    accessTokenGlobal: 'd497d57f-8ef1-4580-9b26-b51155b0ddd4',
    userNameGlobal: 'APIJenningsUsername',
    passwordGlobal: 'APIPassword123',
    custodianUrl: 'https://custodian-qa.fsbtech.com/',
    custodianUsername: 'MahendraM',
    custodianPassword: 'r#nfctrcoAZ0',
    userNameFullCoverBet: 'APIJenningsbet3',
    passwordFullCoverBet: 'APIPassword123',
    userNameForeCastBets: 'APIJenningsbet3',
    passwordForeCastBets: 'APIPassword123',
    userName7FDTo11FDBet: 'APIJenningsbet1',
    password7FDTo11FDBet: 'APIPassword123',
    userName11FDTo15FDBet: 'APIJenningsbet2',
    password11FDTo15FDBet: 'APIPassword123',
    currencyCode: 'GBP',
    randomDeposit: '',
    requestBBody: '',
    level1ResponseTime: '6000',
    level2ResponseTime: '20000',        
    level3ResponseTime: '60000',
    level4ResponseTime: '120000',
    level1ResponseTime: '6000'    
}