
module.exports={
    uiUrl: '',
    url: 'https://betgoodwin.preprod.fsbtech.com/fsb-api-rest',
    authUsername: 'betgoodwin',
    authPassword: 'Ihr6U7RvCUAj50L65B71',
    clientId: 'betgoodwinweb',
    clientSecret: 'QIsReY5p8X',
    accessTokenGlobal: '9acda5c2-ac3a-47b9-87e7-97d15657aec3',
    userNameGlobal: 'APIBetgoodwin',
    passwordGlobal: 'Automation123',
    custodianUrl: 'https://custodian.preprod.fsbtech.com/',
    custodianUsername: 'PavanD',
    custodianPassword: 'h#0pEXhhttos',
    userNameFullCoverBet: 'APIGoodwin3',
    passwordFullCoverBet: 'APIPassword123',
    userNameForeCastBets: 'APIGoodwin3',
    passwordForeCastBets: 'APIPassword123',
    userName7FDTo11FDBet: 'APIGoodwin1',
    password7FDTo11FDBet: 'APIPassword123',
    userName11FDTo15FDBet: 'APIGoodwint2',
    password11FDTo15FDBet: 'APIGoodwin123',
    currencyCode: 'GBP',
    randomDeposit: '',
    requestBBody: '',
    level1ResponseTime: '6000',
    level2ResponseTime: '20000',        
    level3ResponseTime: '60000',
    level4ResponseTime: '120000',
    level1ResponseTime: '6000'    
}