
module.exports={
    uiUrl: '',
    url: 'https://casinotime.qa.fsbtech.com/fsb-api-rest',
    authUsername: 'casinotime',
    authPassword: '&C4z1n0!',
    clientId: 'casinotimeweb',
    clientSecret: '7WkKy7tWTj',
    accessTokenGlobal: 'd497d57f-8ef1-4580-9b26-b51155b0ddd4',
    userNameGlobal: 'APITest@gmail.com',
    passwordGlobal: 'Automation123',
    custodianUrl: 'https://custodian-qa.fsbtech.com/',
    custodianUsername: 'AnjanaP',
    custodianPassword: '!vqbami0sEzC',
    userNameFullCoverBet: 'APICasinotime3@gmail.com',
    passwordFullCoverBet: 'APIPassword123',
    userNameForeCastBets: 'APICasinotime3@gmail.com',
    passwordForeCastBets: 'APIPassword123',
    userName7FDTo11FDBet: 'APICasinotime1@gmail.com',
    password7FDTo11FDBet: 'APIPassword123',
    userName11FDTo15FDBet: 'APICasinotime1@gmail.com',
    password11FDTo15FDBet: 'APIPassword123',
    currencyCode: 'CWD',
    randomDeposit: '',
    requestBBody: '',
    level1ResponseTime: '6000',
    level2ResponseTime: '20000',        
    level3ResponseTime: '60000',
    level4ResponseTime: '120000',
    level1ResponseTime: '6000'    
}